### ISSUE TITLE
Fix and edit operations functionality

### ISSUE THREAD

**Issue by vsots** [vsots/calculator#5]
Currently, inputting equals (=) results in an error:
```
Uncaught TypeError: op is not a function
    at equalsInput (App.tsx:169:20)
    at editInput (App.tsx:63:29)
    at onClick (App.tsx:216:66)
    at HTMLUnknownElement.callCallback2 (react-dom_client.js?v=7637b56e:3672:22)
    at Object.invokeGuardedCallbackDev (react-dom_client.js?v=7637b56e:3697:24)
    at invokeGuardedCallback (react-dom_client.js?v=7637b56e:3731:39)
    at invokeGuardedCallbackAndCatchFirstError (react-dom_client.js?v=7637b56e:3734:33)
    at executeDispatch (react-dom_client.js?v=7637b56e:7014:11)
    at processDispatchQueueItemsInOrder (react-dom_client.js?v=7637b56e:7034:15)
    at processDispatchQueue (react-dom_client.js?v=7637b56e:7043:13)
```
Fix this by handling cases when either of `firstNumber`, `secondNumber`, or `operation.current` are falsy.

If secondNumber not inputted, commit `operation.current` on `firstNumber`.

**Comment by vsots** [comment]
https://github.com/vsots/calculator/pull/6
